import type { AuraDef, AuraId, EnemyDef, EnemyId } from './types';

/**
 * The enemy roster (§4.3, §11.1): three types per region, plus the
 * Summoner's Imps, and the Abyss's own four (§9). Body colours are content data, carried over from the
 * legacy grunt/fast/tank/splitter/healer/shielded/siege/blinker/burrower/
 * harbinger/chorus/leech where one existed.
 */
export const ENEMIES: readonly EnemyDef[] = [
  {
    id: 'grunt',
    name: 'Grunt',
    icon: 'orc-head',
    text: 'Walks in and hits the wall. The baseline.',
    hp: 1,
    speed: 75,
    radius: 21,
    damage: 1,
    attackInterval: 1,
    armor: 0,
    pack: [1, 1],
    xp: 1,
    mass: 1,
    shape: 'circle',
    color: '#d04848',
    borderColor: '#ffffff',
    verb: { kind: 'walker' },
    lore: 'The Blight wears the dead of the Fields like a coat, and sends them first.',
  },
  {
    id: 'runner',
    name: 'Runner',
    icon: 'running-ninja',
    text: 'Fast, and comes in packs. Rate or area beats it.',
    hp: 0.45,
    speed: 135,
    radius: 16,
    damage: 0.6,
    attackInterval: 0.8,
    armor: 0,
    pack: [4, 6],
    xp: 0.5,
    mass: 0.6,
    shape: 'diamond',
    color: '#f1c40f',
    borderColor: '#7a6500',
    verb: { kind: 'walker' },
    lore: 'They hunt as the wolves of the Fields once did: low, many, and never alone.',
  },
  {
    id: 'brute',
    name: 'Brute',
    icon: 'rock-golem',
    text: 'Armoured. Big hits beat many small ones.',
    hp: 4,
    speed: 42,
    radius: 31,
    damage: 3,
    attackInterval: 1.4,
    armor: 0.35,
    pack: [1, 1],
    xp: 4,
    mass: 3,
    shape: 'plated',
    color: '#2c5b8f',
    borderColor: '#9aa7b5',
    verb: { kind: 'walker' },
    lore: 'Old siege plate, grown over. Whatever is inside stopped feeling pain long ago.',
  },
  {
    id: 'splitter',
    name: 'Splitter',
    icon: 'transparent-slime',
    text: 'Splits in three when slain. Area beats the pieces.',
    hp: 1.6,
    speed: 62,
    radius: 25,
    damage: 1,
    attackInterval: 1,
    armor: 0,
    pack: [1, 2],
    xp: 1,
    mass: 1.2,
    shape: 'circle',
    color: '#9b59ff',
    borderColor: '#d3b3ff',
    verb: { kind: 'split', count: 3, hp: 0.3, scale: 0.6, reward: 0.25 },
    lore: 'Mire spawn. Cut one and the water simply makes more of it.',
  },
  {
    id: 'spitter',
    name: 'Spitter',
    icon: 'droplets',
    text: 'Stops at range and lobs shots. Reach it, or kill it first.',
    hp: 0.9,
    speed: 70,
    radius: 22,
    damage: 0.9,
    attackInterval: 1,
    armor: 0,
    pack: [1, 2],
    xp: 1,
    mass: 1,
    shape: 'hexagon',
    color: '#a9752f',
    borderColor: '#f0d3a0',
    verb: { kind: 'ranged', standoff: 290, interval: 2.6, shotSpeed: 260 },
    lore: 'It fills its throat with bog-water and patience. It has a great deal of both.',
  },
  {
    id: 'mender',
    name: 'Mender',
    icon: 'healing',
    text: 'Heals the enemies around it. Burst it down first.',
    hp: 1.2,
    speed: 58,
    radius: 22,
    damage: 0.7,
    attackInterval: 1.2,
    armor: 0,
    pack: [1, 1],
    xp: 1.5,
    mass: 1,
    shape: 'circle',
    color: '#27ae60',
    borderColor: '#0e3a1d',
    verb: { kind: 'heal', radius: 150, interval: 2, fraction: 0.12 },
    lore: 'The Mire does not let its children die easily. The Menders see to that.',
  },
  {
    id: 'shieldbearer',
    name: 'Shieldbearer',
    icon: 'roman-shield',
    text: 'Its shield turns shots from the front. Chains, blades and blasts get round.',
    hp: 1.5,
    speed: 55,
    radius: 25,
    damage: 1.2,
    attackInterval: 1.1,
    armor: 0,
    pack: [1, 2],
    xp: 1.4,
    mass: 2,
    shape: 'square',
    color: '#5f7f9c',
    borderColor: '#d8e6f2',
    verb: { kind: 'shield', arc: 1.1 },
    lore: 'The Wastes made glass of an army. A few still march behind what is left of their shields.',
  },
  {
    id: 'burrower',
    name: 'Burrower',
    icon: 'mole',
    text: 'Travels underground and surfaces at the wall. Close-range weapons catch it.',
    hp: 1.1,
    speed: 80,
    radius: 22,
    damage: 1.3,
    attackInterval: 0.9,
    armor: 0,
    pack: [1, 3],
    xp: 1.2,
    mass: 1.2,
    shape: 'circle',
    color: '#8a6a43',
    borderColor: '#e2c89a',
    verb: { kind: 'burrow', surface: 150 },
    lore: 'You hear it before you see it: glass grinding on glass, somewhere under your feet.',
  },
  {
    id: 'shardling',
    name: 'Shardling',
    icon: 'crystal-cluster',
    text: 'Bursts into shards when slain. Kill it far from the wall.',
    hp: 0.7,
    speed: 95,
    radius: 18,
    damage: 0.8,
    attackInterval: 0.9,
    armor: 0,
    pack: [3, 5],
    xp: 0.7,
    mass: 0.7,
    shape: 'triangle',
    color: '#7fd6e0',
    borderColor: '#1f5a63',
    verb: { kind: 'shards', count: 3, reach: 170, damage: 0.6 },
    lore: 'A splinter of the Wastes that learned to walk. It keeps its edges for whoever kills it.',
  },
  {
    id: 'bomber',
    name: 'Bomber',
    icon: 'falling-bomb',
    text: 'Explodes when slain. Kill it far away, never at the wall.',
    hp: 1.3,
    speed: 70,
    radius: 24,
    damage: 1,
    attackInterval: 1.2,
    armor: 0,
    pack: [1, 2],
    xp: 1.3,
    mass: 1.2,
    shape: 'circle',
    color: '#c0392b',
    borderColor: '#ffcc66',
    verb: { kind: 'explode', radius: 110, damage: 3 },
    lore: 'The Rift fills them with its own fire and sends them to the wall to give it back.',
  },
  {
    id: 'blinker',
    name: 'Blinker',
    icon: 'teleport',
    text: 'Leaps inward every few seconds. Slow it or burst it.',
    hp: 0.9,
    speed: 50,
    radius: 19,
    damage: 1,
    attackInterval: 0.8,
    armor: 0,
    pack: [1, 2],
    xp: 1.1,
    mass: 0.8,
    shape: 'diamond',
    color: '#c56bff',
    borderColor: '#3b1060',
    verb: { kind: 'blink', interval: 2.6, distance: 110 },
    lore: 'Heat-shimmer given a body. It is never quite where you aimed.',
  },
  {
    id: 'siege-engine',
    name: 'Siege Engine',
    icon: 'catapult',
    text: 'Stops beyond your range and bombards the wall. Reach farther, or send drones.',
    hp: 3,
    speed: 40,
    radius: 32,
    damage: 2.2,
    attackInterval: 1.5,
    armor: 0.15,
    pack: [1, 1],
    xp: 3,
    mass: 4,
    shape: 'plated',
    color: '#6b4a2b',
    borderColor: '#f0a050',
    verb: { kind: 'ranged', standoff: 410, interval: 3.2, shotSpeed: 220 },
    lore: 'Old war machines, dragged out of the Rift still burning. Somebody inside still works the arm.',
  },
  {
    id: 'phantom',
    name: 'Phantom',
    icon: 'bat',
    text: 'Fades out of reach on a cycle. Burst it while it shows.',
    hp: 1.2,
    speed: 70,
    radius: 21,
    damage: 1.1,
    attackInterval: 1,
    armor: 0,
    pack: [1, 3],
    xp: 1.3,
    mass: 0.8,
    shape: 'diamond',
    color: '#8fa3c7',
    borderColor: '#e9f0ff',
    verb: { kind: 'phase', cycle: 4, hidden: 1.8 },
    lore: 'The Hollow keeps its dead half in this world. You can only hit the half that is here.',
  },
  {
    id: 'leech',
    name: 'Leech',
    icon: 'fangs-circle',
    text: 'Drains your ultimate when it bites. Kill it before it touches.',
    hp: 0.8,
    speed: 105,
    radius: 18,
    damage: 0.7,
    attackInterval: 0.7,
    armor: 0,
    pack: [2, 4],
    xp: 0.8,
    mass: 0.6,
    shape: 'circle',
    color: '#5c2a4a',
    borderColor: '#ff7ab0',
    verb: { kind: 'leech', drain: 0.12 },
    lore: 'It does not want your stone. It wants the light inside it.',
  },
  {
    id: 'summoner',
    name: 'Summoner',
    icon: 'pentagram-rose',
    text: 'Calls Imps from range until it dies. Kill it first.',
    hp: 2,
    speed: 50,
    radius: 25,
    damage: 0.8,
    attackInterval: 1.2,
    armor: 0,
    pack: [1, 1],
    xp: 2.5,
    mass: 1.5,
    shape: 'hexagon',
    color: '#3d2c6b',
    borderColor: '#b48cff',
    verb: { kind: 'summon', enemy: 'imp', count: 2, interval: 3.5, standoff: 300 },
    lore: 'A crowned thing with no crown. It calls its court out of the dark, two at a time.',
  },
  {
    id: 'imp',
    name: 'Imp',
    icon: 'wizard-face',
    text: 'A Summoner’s servant: weak, quick and many.',
    hp: 0.3,
    speed: 115,
    radius: 14,
    damage: 0.5,
    attackInterval: 0.8,
    armor: 0,
    pack: [1, 1],
    xp: 0.2,
    mass: 0.5,
    shape: 'triangle',
    color: '#6c4bb4',
    borderColor: '#e0d0ff',
    verb: { kind: 'walker' },
    lore: 'Nobody has seen an Imp without a Summoner behind it. Nobody has looked very hard.',
  },
  {
    id: 'harbinger',
    name: 'Harbinger',
    icon: 'all-seeing-eye',
    text: 'Its gaze silences one weapon for 4 s. Burst it down first.',
    hp: 2.2,
    speed: 45,
    radius: 27,
    damage: 1,
    attackInterval: 1.2,
    armor: 0.05,
    pack: [1, 1],
    xp: 2.5,
    mass: 2,
    shape: 'hexagon',
    color: '#2b2b3a',
    borderColor: '#ff6060',
    verb: { kind: 'silence', standoff: 320, interval: 5, seconds: 4 },
    lore: 'The Blight’s own eye. Where it looks, the light forgets what it was doing.',
  },
  {
    id: 'chorus',
    name: 'Chorus',
    icon: 'star-formation',
    text: 'Three bodies, one life. Area hits all three at once.',
    hp: 2.4,
    speed: 60,
    radius: 20,
    damage: 0.8,
    attackInterval: 1,
    armor: 0,
    pack: [1, 1],
    xp: 0.9,
    mass: 1,
    shape: 'circle',
    color: '#d6b4ff',
    borderColor: '#4a2a72',
    verb: { kind: 'chorus', count: 3 },
    lore: 'Three voices, one song. Silence one and the others stop singing too.',
  },
  // ── The Abyss (§9) ─────────────────────────────────────────────────────
  {
    id: 'husk',
    name: 'Husk',
    icon: 'cracked-shield',
    text: 'Its shell swallows the first six hits. Many small hits beat it.',
    hp: 1.5,
    speed: 55,
    radius: 26,
    damage: 1.2,
    attackInterval: 1.1,
    armor: 0,
    pack: [1, 2],
    xp: 1.6,
    mass: 1.6,
    shape: 'plated',
    color: '#5c4a32',
    borderColor: '#d9c08a',
    verb: { kind: 'carapace', hits: 6 },
    lore: 'Something crawled into the armour of the drowned and never came out.',
  },
  {
    id: 'ram',
    name: 'Ram',
    icon: 'armor-punch',
    text: 'Stops, then charges. Slow it, or knock it back.',
    hp: 1.4,
    speed: 46,
    radius: 24,
    damage: 2,
    attackInterval: 1.2,
    armor: 0.04,
    pack: [1, 2],
    xp: 1.4,
    mass: 2,
    shape: 'triangle',
    color: '#8a2f2f',
    borderColor: '#ffb3a0',
    verb: { kind: 'charge', interval: 3.2, seconds: 0.9, speed: 4.5 },
    lore: 'It does not see the tower. It sees a wall, and it hates walls.',
  },
  {
    id: 'wardstone',
    name: 'Wardstone',
    icon: 'stone-block',
    text: 'Shields everything near it. Break it first, from range.',
    hp: 2.5,
    speed: 40,
    radius: 28,
    damage: 1,
    attackInterval: 1.2,
    armor: 0.03,
    pack: [1, 1],
    xp: 2.5,
    mass: 3,
    shape: 'hexagon',
    color: '#3b4a5c',
    borderColor: '#9fe0ff',
    verb: { kind: 'ward', standoff: 300, radius: 150, shield: 0.4 },
    lore: 'A standing stone from a temple nobody remembers, still keeping its promise.',
  },
  {
    id: 'maw',
    name: 'Maw',
    icon: 'fangs-circle',
    text: 'Feeds on the fallen to heal and grow. Kill it first.',
    hp: 3,
    speed: 48,
    radius: 29,
    damage: 2,
    attackInterval: 1.2,
    armor: 0,
    pack: [1, 1],
    xp: 3,
    mass: 2.5,
    shape: 'circle',
    color: '#4a1a2a',
    borderColor: '#ff7a9a',
    verb: { kind: 'devour', radius: 130, heal: 0.3, grow: 0.12, feeds: 6 },
    lore: 'The Abyss keeps nothing. What falls here is eaten before it is cold.',
  },
];

export const ENEMY_BY_ID: Readonly<Record<EnemyId, EnemyDef>> = Object.fromEntries(
  ENEMIES.map((e) => [e.id, e]),
) as Record<EnemyId, EnemyDef>;

/**
 * Elite auras (§4.3). An elite is a regular body with ×8 HP and one aura;
 * Region 1's elites wear none. Numbers live in `BALANCE.elites`.
 */
export const AURAS: readonly AuraDef[] = [
  { id: 'haste', name: 'Swift', icon: 'wingfoot', text: 'It and its neighbours move faster.', radius: 160 },
  { id: 'regen', name: 'Regen', icon: 'regeneration', text: 'It and its neighbours regenerate.', radius: 160 },
  { id: 'shield', name: 'Shield', icon: 'energy-shield', text: 'Its neighbours take half damage. Kill it first.', radius: 160 },
  { id: 'split', name: 'Split', icon: 'split-arrows', text: 'Bursts into three of its kind when slain.', radius: 0 },
  { id: 'vengeful', name: 'Vengeful', icon: 'enrage', text: 'Its death enrages everything near it.', radius: 200 },
];

export const AURA_BY_ID: Readonly<Record<AuraId, AuraDef>> = Object.fromEntries(
  AURAS.map((a) => [a.id, a]),
) as Record<AuraId, AuraDef>;
